---
layout: post
category: Java
title: java异常处理
tags: Java
---

## 异常

Throwable 可以用来表示任何可以作为异常抛出的类，分为两种： **Error**  和 **Exception**。其中 Error 用来表示 JVM 无法处理的错误，Exception 分为两种：

1.  **受检异常** ：需要用 try...catch... 语句捕获并进行处理，并且可以从异常中恢复；
2.  **非受检异常** ：是程序运行时错误，例如除 0 会引发 Arithmetic Exception，此时程序奔溃并且无法恢复。

> [Java 入门之异常处理](https://www.tianmaying.com/tutorial/Java-Exception) 
>
> [Java 异常的面试问题及答案 -Part 1](http://www.importnew.com/7383.html)

## 种类

![img](https://cdn.jsdelivr.net/gh/mafulong/mdPic@vv6/v6/202503312007364.png)

![](https://cdn.jsdelivr.net/gh/mafulong/mdPic@master/images/41f472b9fea27faf7b0bcbd95e6a594a.png)
检查性异常：最具代表的检查性异常是用户错误或问题引起的异常，这是程序员无法预见的。例如要打开一个不存在文件时，一个异常就发生了，这些异常在编译时不能被简单地忽略。

运行时异常： 运行时异常是可能被程序员避免的异常。与检查性异常相反，运行时异常可以在编译时被忽略。

错误： 错误不是异常，而是脱离程序员控制的问题。错误在代码中通常被忽略。例如，当栈溢出时，一个错误就发生了，它们在编译也检查不到的。

## Java 内置异常类
Java 语言定义了一些异常类在 java.lang 标准包中。

## 异常方法

    1	public String getMessage()
    返回关于发生的异常的详细信息。这个消息在Throwable 类的构造函数中初始化了。
    2	public Throwable getCause()
    返回一个Throwable 对象代表异常原因。
    3	public String toString()
    使用getMessage()的结果返回类的串级名字。
    4	public void printStackTrace()
    打印toString()结果和栈层次到System.err，即错误输出流。
    5	public StackTraceElement [] getStackTrace()
    返回一个包含堆栈层次的数组。下标为0的元素代表栈顶，最后一个元素代表方法调用堆栈的栈底。
    6	public Throwable fillInStackTrace()
    用当前的调用栈层次填充Throwable 对象栈层次，添加到栈层次任何先前信息中。

## 捕获异常

    try
    {
    // 程序代码
    }catch(ExceptionName e1)
    {
    //Catch 块
    }

## throws/throw 关键字：
如果一个方法没有捕获一个检查性异常，那么该方法必须使用 throws 关键字来声明。throws 关键字放在方法签名的尾部。

也可以使用 throw 关键字抛出一个异常，无论它是新实例化的还是刚捕获到的。
```java
import java.io.*;
public class className
{
  public void deposit(double amount) throws RemoteException
  {
    // Method implementation
    throw new RemoteException();
  }
  //Remainder of class definition
}
```

## finally关键字
finally 关键字用来创建在 try 代码块后面执行的代码块。

无论是否发生异常，finally 代码块中的代码总会被执行。

在 finally 代码块中，可以运行清理类型等收尾善后性质的语句。

finally 代码块出现在 catch 代码块最后，语法如下：
```java
try{
  // 程序代码
}catch(异常类型1 异常的变量名1){
  // 程序代码
}catch(异常类型2 异常的变量名2){
  // 程序代码
}finally{
  // 程序代码
}
```

## 声明自定义异常
在 Java 中你可以自定义异常。编写自己的异常类时需要记住下面的几点。
所有异常都必须是 Throwable 的子类。

如果希望写一个检查性异常类，则需要继承 Exception 类。

如果你想写一个运行时异常类，那么需要继承 RuntimeException 类。
可以像下面这样定义自己的异常类：
```java
class MyException extends Exception{
}
```
只继承Exception 类来创建的异常类是检查性异常类。

## 描述Java 7 ARM(Automatic Resource Management，自动资源管理)特征和多个catch块的使用

答：如果一个try块中有多个异常要被捕获，catch块中的代码会变丑陋的同时还要用多余的代码来记录异常。有鉴于此，Java 7的一个新特征是：一个catch子句中可以捕获多个异常。示例代码如下：

```java
catch(IOException | SQLException | Exception ex){
     logger.error(ex);
     throw new MyException(ex.getMessage());
}
```



## try-with-resources

大多数情况下，当忘记关闭资源或因资源耗尽出现运行时异常时，我们只是用finally子句来关闭资源。这些异常很难调试，我们需要深入到资源使用的每一步来确定是否已关闭。比如try里有file.readline和finally file.close都可能抛出异常，这样异常会覆盖。





因此，Java 7用try-with-resources进行了改进：在try子句中能创建一个资源对象，当程序的执行完try-catch之后，运行环境自动关闭资源。下面是这方面改进的示例代码：

```java
class MyResource implements AutoCloseable {
    MyResource() {
    }

    public void close() throws Exception {
        System.out.println("关闭自定义资源");
    }
}



try (MyResource mr = new MyResource()) {
            System.out.println("MyResource created in try-with-resources");
        } catch (Exception e) {
            e.printStackTrace();
        }
```



实现上，是try里自动加了close的代码在try的字节码代码块里。[参考](https://javabetter.cn/exception/try-with-resources.html)

## 最佳实践

- try 块中的 return 语句执行成功后，并不会马上返回，而是继续执行 finally 块中的语句，如果 finally 块中也存在 return 语句，那么 try 块中的 return 就将被覆盖。
- 抛出具体定义的检查性异常而不是-exception
- 自定义异常时不要丢失堆栈跟踪
- finally 块中不要抛出任何异常。 如果在 finally 块中抛出异常，可能会导致原始异常被掩盖。比如说上例中，一旦 cleanup 抛出异常，someMethod 中的异常将会被覆盖。
- `printStackTrace()` **会阻塞 I/O**，在高并发环境下，可能会造成**性能问题**。  频繁调用 `printStackTrace()` 可能会**影响垃圾回收（GC）**，因为 `Throwable.fillInStackTrace()` 需要收集完整的堆栈信息。
- 对于不打算处理的异常，直接使用 try-finally，不用 catch
- 记住早 throw 晚 catch 原则。 “早 throw, 晚 catch” 是 Java 中的一种异常处理原则。这个原则指的是在代码中尽可能早地抛出异常，以便在异常发生时能够及时地处理异常。同时，在 catch 块中尽可能晚地捕获异常，以便在捕获异常时能够获得更多的上下文信息，从而更好地处理异常。
- 切勿在代码中使用异常来进行流程控制